version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=huiji.233
      - POSTGRES_DB=dev
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db   
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:huiji.233@db:5432/dev
    ports:
      - "12000:12000"
    networks:
      - app-net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL_DEV: ${NEXT_PUBLIC_API_URL_DEV}
    restart: always
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL_DEV=http://127.0.0.1:12000
    ports:
      - "3000:3000"
    networks:
      - app-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net


volumes:
  db_data:

networks:
  app-net:
    driver: bridge
