version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - test.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - test.env      
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "12000:12000"
    networks:
      - app-net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL_DEV: ${NEXT_PUBLIC_API_URL_DEV}
    restart: always
    depends_on:
      - api
    env_file:
      - test.env
    environment:
      - NEXT_PUBLIC_API_URL_DEV
    ports:
      - "3000:3000"
    networks:
      - app-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net


volumes:
  db_data:

networks:
  app-net:
    driver: bridge
